import type {Metadata} from "next";
import "./globals.css";
import {AuthProvider} from './auth/AuthContext';
import React from 'react';
import Navbar from './Navbar';
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        </head>
        <body
            className={'antialiased'}
        >
        <AuthProvider>
            <Navbar/>
            <ToastContainer position="top-right" autoClose={3000} hideProgressBar={false} newestOnTop closeOnClick
                            pauseOnFocusLoss draggable pauseOnHover/>
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
